version: '3'
volumes:
    sql-db:
    redis-db:
services:
    postgres:
        image: postgres:14.2-alpine
        env_file:
            - .env
            - db.env
        volumes:
            - type: volume
              source: sql-db
              target: /var/lib/postgresql/data
    redis:
        image: redis:7.0-alpine
        ports:
            - '6379:6379'
        expose:
            - 6379
        command: ["redis-server"]
        hostname: redis
        env_file:
            - .env
            - redis.env
        volumes:
            - type: volume
              source: redis-db
              target: /data
