version: '3'

networks:
    internal: {}
    public: {}

services:
    traefik:
        image: "traefik:v2.9"
        container_name: traefik
        restart: on-failure
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:8000"
        ports:
            - "8000:8000"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - public
    app:
        image: thatsa-gg/scholar-glenna-app:latest
        env_file:
            - common.env
            - ../config.env
        expose:
            - 3000
        restart: on-failure
        depends_on:
            postgres:
                condition: service_healthy
            bootstrap:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.glenna.rule=Host(`localhost`)"
            - "traefik.http.routers.glenna.entrypoints=web"
        networks:
            - public
            - internal
    bot:
        image: thatsa-gg/scholar-glenna-bot:latest
        env_file:
            - common.env
            - ../config.env
        restart: on-failure
        depends_on:
            postgres:
                condition: service_healthy
            bootstrap:
                condition: service_completed_successfully
            redis:
                condition: service_healthy
        networks:
            - internal
    redis:
        image: redis:7.0-alpine
        volumes:
            - type: volume
              source: redis-db
              target: /data
        restart: on-failure
        healthcheck:
            test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - internal
    postgres:
        image: postgres:15.2-alpine
        env_file: postgres.env
        volumes:
            - type: volume
              source: sql-db
              target: /var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - internal
    bootstrap:
        image: thatsa-gg/scholar-glenna-bootstrap:latest
        env_file:
            - common.env
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - internal

volumes:
    sql-db:
    redis-db:
