version: '3'

services:
    app:
    bot:
    postgres:
        image: postgres:15.2-alpine
        env_file: development.env
        volumes:
            - type: volume
              source: sql-db
              target: /var/lib/postgresql/data
    redis:
        image: redis:7.0-alpine
        env_file: development.env
        volumes:
            - type: volume
              source: redis-db
              target: /data

volumes:
    sql-db:
    redis-db:
