version: '3'

services:
  devcontainer:
    build:
      context: ../.devcontainer
      dockerfile: Dockerfile
      args:
        VARIANT: "bullseye"
    env_file:
        - ../docker/.env
        - ../docker/db.env
        - ../docker/redis.env
        - ../config.env
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    user: vscode
