version: '3'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    env_file:
        - ../docker/.env
        - ../docker/db.env
        - ../docker/redis.env
        - ../config.env
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
